//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWC_VoiceAssistent.projects.db {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsGerman {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsGerman() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DWC_VoiceAssistent.projects.db.SettingsGerman", typeof(SettingsGerman).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erwachsen ähnelt.
        /// </summary>
        internal static string DWC_Settings_Age_Selection_Adult {
            get {
                return ResourceManager.GetString("DWC_Settings_Age_Selection_Adult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kind ähnelt.
        /// </summary>
        internal static string DWC_Settings_Age_Selection_Child {
            get {
                return ResourceManager.GetString("DWC_Settings_Age_Selection_Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nur vertifizierte User ähnelt.
        /// </summary>
        internal static string DWC_Settings_Button_OnlyVerifyUsers {
            get {
                return ResourceManager.GetString("DWC_Settings_Button_OnlyVerifyUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktiviert ähnelt.
        /// </summary>
        internal static string DWC_Settings_Buttons_Active {
            get {
                return ResourceManager.GetString("DWC_Settings_Buttons_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jeder ähnelt.
        /// </summary>
        internal static string DWC_Settings_Buttons_EveryOne {
            get {
                return ResourceManager.GetString("DWC_Settings_Buttons_EveryOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deaktiviert ähnelt.
        /// </summary>
        internal static string DWC_Settings_Buttons_InActive {
            get {
                return ResourceManager.GetString("DWC_Settings_Buttons_InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nur Freunde ähnelt.
        /// </summary>
        internal static string DWC_Settings_Buttons_OnlyFriends {
            get {
                return ResourceManager.GetString("DWC_Settings_Buttons_OnlyFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Farbauswahl ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_Color {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Autostart ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_Generell_AutoStart_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_Generell_AutoStart_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimiere Fenster beim schließen ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_Generell_KeepWindowAlife_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_Generell_KeepWindowAlife_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benachrichtigungen ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_Generell_Message_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_Generell_Message_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rundes Desighn ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_Generell_RoundedDesighn_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_Generell_RoundedDesighn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willkommens Nachricht ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_Generell_WelcomeMessage_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_Generell_WelcomeMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System Einstellungen ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_System {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprache ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_System_Language_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_System_Language_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprach Reaktions Befehl ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_System_ListenName_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_System_ListenName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzer Name ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_System_UserName_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_System_UserName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Theme Auswahl ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_Theme {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stimm Optionen ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_Voice {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_Voice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alter ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_Voice_Age_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_Voice_Age_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geschlecht ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_Voice_Gender_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_Voice_Gender_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lautstärke ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_Voice_Volum_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_Voice_Volum_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verbundene Konten ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Accounts {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprach Assistent ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Assistent {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Assistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chat ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Chat {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dienste löschen ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_DeleteDienste {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_DeleteDienste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aussehen ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Desighn {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Desighn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datenschutzerklärung ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Eula {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Eula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erweiterungen ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Extention {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Extention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Freundeseinstellungen ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Friends {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Heading {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tasten Kombinationen ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_HotKey {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_HotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprache ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Language {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abmelden ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Logout {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mikrofon ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Microphone {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Microphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Privatsphäreneinstellung ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Privacy {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anwendung ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Program {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zurücksetzen ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Reset {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sicherheit ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Security {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen speichern ähnelt.
        /// </summary>
        internal static string DWC_Settings_SaveButton_Save_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_SaveButton_Save_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die und schließen (Escape) ähnelt.
        /// </summary>
        internal static string DWC_Settings_SaveButton_SaveDescription_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_SaveButton_SaveDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frau ähnelt.
        /// </summary>
        internal static string DWC_Settings_Voice_Selection_Female {
            get {
                return ResourceManager.GetString("DWC_Settings_Voice_Selection_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mann ähnelt.
        /// </summary>
        internal static string DWC_Settings_Voice_Selection_Male {
            get {
                return ResourceManager.GetString("DWC_Settings_Voice_Selection_Male", resourceCulture);
            }
        }
    }
}
