//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWC_VoiceAssistent.projects.db {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsEnglish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsEnglish() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DWC_VoiceAssistent.projects.db.SettingsEnglish", typeof(SettingsEnglish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adult ähnelt.
        /// </summary>
        internal static string DWC_Settings_Age_Selection_Adult {
            get {
                return ResourceManager.GetString("DWC_Settings_Age_Selection_Adult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Child ähnelt.
        /// </summary>
        internal static string DWC_Settings_Age_Selection_Child {
            get {
                return ResourceManager.GetString("DWC_Settings_Age_Selection_Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only Verify Users ähnelt.
        /// </summary>
        internal static string DWC_Settings_Button_OnlyVerifyUsers {
            get {
                return ResourceManager.GetString("DWC_Settings_Button_OnlyVerifyUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Active ähnelt.
        /// </summary>
        internal static string DWC_Settings_Buttons_Active {
            get {
                return ResourceManager.GetString("DWC_Settings_Buttons_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Every one ähnelt.
        /// </summary>
        internal static string DWC_Settings_Buttons_EveryOne {
            get {
                return ResourceManager.GetString("DWC_Settings_Buttons_EveryOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inactive ähnelt.
        /// </summary>
        internal static string DWC_Settings_Buttons_InActive {
            get {
                return ResourceManager.GetString("DWC_Settings_Buttons_InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only Friends ähnelt.
        /// </summary>
        internal static string DWC_Settings_Buttons_OnlyFriends {
            get {
                return ResourceManager.GetString("DWC_Settings_Buttons_OnlyFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color selection ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_Color {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Autostart ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_Generell_AutoStart_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_Generell_AutoStart_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimize Window on close ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_Generell_KeepWindowAlife_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_Generell_KeepWindowAlife_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Notifications ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_Generell_Message_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_Generell_Message_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rounded Desighn ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_Generell_RoundedDesighn_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_Generell_RoundedDesighn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welcome Message ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_Generell_WelcomeMessage_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_Generell_WelcomeMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System Options ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_System {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_System_Language_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_System_Language_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Liste Name ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_System_ListenName_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_System_ListenName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User Name ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_System_UserName_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_System_UserName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Theme selection ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_Theme {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Voice Options ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_Voice {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_Voice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Age ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_Voice_Age_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_Voice_Age_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gender ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_Voice_Gender_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_Voice_Gender_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Volum ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_Voice_Volum_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_Voice_Volum_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connected Accounts ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Accounts {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Voice Assistent ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Assistent {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Assistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chat ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Chat {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Services ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_DeleteDienste {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_DeleteDienste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Design ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Desighn {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Desighn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eula ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Eula {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Eula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extentions ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Extention {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Extention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Friends Setting ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Friends {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Heading {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hot Keys ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_HotKey {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_HotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Language {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logout ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Logout {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Microphone ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Microphone {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Microphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Privacy Settings ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Privacy {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Program ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Program {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Reset {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Security ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Security {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Settings ähnelt.
        /// </summary>
        internal static string DWC_Settings_SaveButton_Save_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_SaveButton_Save_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die and close (Escape) ähnelt.
        /// </summary>
        internal static string DWC_Settings_SaveButton_SaveDescription_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_SaveButton_SaveDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Female ähnelt.
        /// </summary>
        internal static string DWC_Settings_Voice_Selection_Female {
            get {
                return ResourceManager.GetString("DWC_Settings_Voice_Selection_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Male ähnelt.
        /// </summary>
        internal static string DWC_Settings_Voice_Selection_Male {
            get {
                return ResourceManager.GetString("DWC_Settings_Voice_Selection_Male", resourceCulture);
            }
        }
    }
}
