//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWC_VoiceAssistent.projects.db.systeminfo {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Russian {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Russian() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DWC_VoiceAssistent.projects.db.systeminfo.Russian", typeof(Russian).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AD ähnelt.
        /// </summary>
        internal static string Ad__Text {
            get {
                return ResourceManager.GetString("Ad__Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Все компоненты ähnelt.
        /// </summary>
        internal static string AllComponents_Text {
            get {
                return ResourceManager.GetString("AllComponents_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DHCP ähnelt.
        /// </summary>
        internal static string Dhcp_Text {
            get {
                return ResourceManager.GetString("Dhcp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Брандмауэр ähnelt.
        /// </summary>
        internal static string Firewall_Text {
            get {
                return ResourceManager.GetString("Firewall_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Графическая карта (GPU) ähnelt.
        /// </summary>
        internal static string Graphicscard_Text {
            get {
                return ResourceManager.GetString("Graphicscard_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Мейнборд ähnelt.
        /// </summary>
        internal static string Mainboard_Text {
            get {
                return ResourceManager.GetString("Mainboard_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Оборудование ähnelt.
        /// </summary>
        internal static string Menu_Hardware {
            get {
                return ResourceManager.GetString("Menu_Hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Программное обеспечение ähnelt.
        /// </summary>
        internal static string Menu_Software {
            get {
                return ResourceManager.GetString("Menu_Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die USB ähnelt.
        /// </summary>
        internal static string Menu_Usb_Text {
            get {
                return ResourceManager.GetString("Menu_Usb_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Микрофон ähnelt.
        /// </summary>
        internal static string Mikrophone_Text {
            get {
                return ResourceManager.GetString("Mikrophone_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Сеть ähnelt.
        /// </summary>
        internal static string Network_Text {
            get {
                return ResourceManager.GetString("Network_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Принтер ähnelt.
        /// </summary>
        internal static string Printer_Text {
            get {
                return ResourceManager.GetString("Printer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Процесс ähnelt.
        /// </summary>
        internal static string Process_Text {
            get {
                return ResourceManager.GetString("Process_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Процессор (ЦП) ähnelt.
        /// </summary>
        internal static string Processor_Text {
            get {
                return ResourceManager.GetString("Processor_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Рабочая память (ОЗУ) ähnelt.
        /// </summary>
        internal static string Ram_Text {
            get {
                return ResourceManager.GetString("Ram_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Жесткий диск ähnelt.
        /// </summary>
        internal static string Storage_Text {
            get {
                return ResourceManager.GetString("Storage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Система ähnelt.
        /// </summary>
        internal static string System_Text {
            get {
                return ResourceManager.GetString("System_Text", resourceCulture);
            }
        }
    }
}
