using DarkWolfCraftSys;
using DWC_VoiceAssistent.projects.system;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Shapes;

namespace DWC_VoiceAssistent.handler.projects.settings.categories
{
    class Language
    {
        /*
        * Creator: Jason H.
        * Date: -
        * Comment: -
        */

        private static readonly Settings settingsWindow = Settings.SettingsWindow;

        public Language()
        {
            loadDB();
            loadImages();
            loadColors();
            loadSettings();
            WindowOverlayManager.updateAllWindowContent(settingsWindow.Language_ContentGrid);

            for (int i = 0; i < settingsWindow.Language_StackPannel.Children.Count; i++)
            {
                Grid grid = settingsWindow.Language_StackPannel.Children[i] as Grid;
                grid.MouseLeftButtonDown += changeLanguage;
            }

        }

        #region Load on Initialization
        private void loadDB()
        {
            settingsWindow.Language_Heading.Content = DWC_VoiceAssistent.projects.db.ProjectDBManager.loadDBValueSettings("Language_Heading");
            settingsWindow.Language_Description.Text = DWC_VoiceAssistent.projects.db.ProjectDBManager.loadDBValueSettings("Language_Description");

            //Language_AutogeneratedInfo

            foreach (Grid grid in settingsWindow.Language_StackPannel.Children)
            {
                if (grid.Children.Count == 6)
                {
                    Label label = grid.Children[4] as Label;

                    label.Content = DWC_VoiceAssistent.projects.db.ProjectDBManager.loadDBValueSettings("Language_AutogeneratedInfo");

                }
            }

        }

        private void loadColors()
        {
            settingsWindow.Language_ContentGrid.Background = ProjectVariables.Theme_LighterDark;
            settingsWindow.Language_Spacer_1.Fill = ProjectVariables.Theme_DarkRectangleAccent;
            settingsWindow.Language_Spacer_2.Fill = ProjectVariables.Theme_DarkRectangleAccent;
            settingsWindow.Language_Spacer_3.Fill = ProjectVariables.Theme_DarkRectangleAccent;
            settingsWindow.Language_Spacer_4.Fill = ProjectVariables.Theme_DarkRectangleAccent;
            settingsWindow.Language_Spacer_5.Fill = ProjectVariables.Theme_DarkRectangleAccent;
            settingsWindow.Language_Spacer_6.Fill = ProjectVariables.Theme_DarkRectangleAccent;
            settingsWindow.Language_Spacer_7.Fill = ProjectVariables.Theme_DarkRectangleAccent;
            settingsWindow.Language_Spacer_8.Fill = ProjectVariables.Theme_DarkRectangleAccent;
            settingsWindow.Language_Spacer_9.Fill = ProjectVariables.Theme_DarkRectangleAccent;
            settingsWindow.Language_Spacer_10.Fill = ProjectVariables.Theme_DarkRectangleAccent;
        }

        private void loadImages()
        {
            //Flag Images
            ProjectVariables.LoadSvgImage("src/countries/Germany.svg", settingsWindow.Language_Image_German);
            ProjectVariables.LoadSvgImage("src/countries/English.svg", settingsWindow.Language_Image_English);
            ProjectVariables.LoadSvgImage("src/countries/Italien.svg", settingsWindow.Language_Image_Italian);
            ProjectVariables.LoadSvgImage("src/countries/French.svg", settingsWindow.Language_Image_French);
            ProjectVariables.LoadSvgImage("src/countries/spanien.svg", settingsWindow.Language_Image_Spain);
            ProjectVariables.LoadSvgImage("src/countries/russia.svg", settingsWindow.Language_Image_Russian);
            ProjectVariables.LoadSvgImage("src/countries/china.svg", settingsWindow.Language_Image_China);
            ProjectVariables.LoadSvgImage("src/countries/brasilien.svg", settingsWindow.Language_Image_Brasil);
            ProjectVariables.LoadSvgImage("src/countries/portugal.svg", settingsWindow.Language_Image_Protugal);
            ProjectVariables.LoadSvgImage("src/countries/japan.svg", settingsWindow.Language_Image_Japan);

            //CheckBox Images
            StackPanel stackPanel = settingsWindow.Language_StackPannel;
            for (int i = 0; i < stackPanel.Children.Count; i++)
            {
                Grid grid = stackPanel.Children[i] as Grid;
                Image image = grid.Children[1] as Image;
                ProjectVariables.LoadSvgImage("src/own/Checked.svg", image);
            }

        }

        private void loadSettings()
        {

            if (ConfigManager.language == "de-DE")
            {
                settingsWindow.Language_Grid_German.Background = ProjectVariables.Theme_DarkRectangleAccent;
                settingsWindow.Language_Image_German_Checked.Visibility = System.Windows.Visibility.Visible;
                settingsWindow.Language_Image_German_Rectangle.Stroke = ProjectVariables.MainColor;
            }
            else if (ConfigManager.language == "en-EN")
            {
                settingsWindow.Language_Grid_English.Background = ProjectVariables.Theme_DarkRectangleAccent;
                settingsWindow.Language_Image_English_Checked.Visibility = System.Windows.Visibility.Visible;
                settingsWindow.Language_Image_English_Rectangle.Stroke = ProjectVariables.MainColor;
            }
            else if (ConfigManager.language == "it-IT")
            {
                settingsWindow.Language_Grid_Itali.Background = ProjectVariables.Theme_DarkRectangleAccent;
                settingsWindow.Language_Image_Italian_Checked.Visibility = System.Windows.Visibility.Visible;
                settingsWindow.Language_Image_Italian_Rectangle.Stroke = ProjectVariables.MainColor;
            }
            else if (ConfigManager.language == "fr-FR")
            {
                settingsWindow.Language_Grid_French.Background = ProjectVariables.Theme_DarkRectangleAccent;
                settingsWindow.Language_Image_French_Checked.Visibility = System.Windows.Visibility.Visible;
                settingsWindow.Language_Image_French_Rectangle.Stroke = ProjectVariables.MainColor;
            }
            else if (ConfigManager.language == "ru-RU")
            {
                settingsWindow.Language_Grid_Russia.Background = ProjectVariables.Theme_DarkRectangleAccent;
                settingsWindow.Language_Image_Russian_Checked.Visibility = System.Windows.Visibility.Visible;
                settingsWindow.Language_Image_Russian_Rectangle.Stroke = ProjectVariables.MainColor;
            }
            else if (ConfigManager.language == "es-ES")
            {
                settingsWindow.Language_Grid_Spain.Background = ProjectVariables.Theme_DarkRectangleAccent;
                settingsWindow.Language_Image_Spain_Checked.Visibility = System.Windows.Visibility.Visible;
                settingsWindow.Language_Image_Spain_Rectangle.Stroke = ProjectVariables.MainColor;
            }
            else if (ConfigManager.language == "chn-CHN")
            {
                settingsWindow.Language_Grid_China.Background = ProjectVariables.Theme_DarkRectangleAccent;
                settingsWindow.Language_Image_China_Checked.Visibility = System.Windows.Visibility.Visible;
                settingsWindow.Language_Image_China_Rectangle.Stroke = ProjectVariables.MainColor;
            }
            else if (ConfigManager.language == "prt-PRT")
            {
                settingsWindow.Language_Grid_Portugal.Background = ProjectVariables.Theme_DarkRectangleAccent;
                settingsWindow.Language_Image_Protugal_Checked.Visibility = System.Windows.Visibility.Visible;
                settingsWindow.Language_Image_Protugal_Rectangle.Stroke = ProjectVariables.MainColor;
            }
            else if (ConfigManager.language == "jpn-JPN")
            {
                settingsWindow.Language_Grid_Japan.Background = ProjectVariables.Theme_DarkRectangleAccent;
                settingsWindow.Language_Image_Japan_Checked.Visibility = System.Windows.Visibility.Visible;
                settingsWindow.Language_Image_Japan_Rectangle.Stroke = ProjectVariables.MainColor;
            }
            else if (ConfigManager.language == "mex-MEX")
            {
                settingsWindow.Language_Grid_Brasil.Background = ProjectVariables.Theme_DarkRectangleAccent;
                settingsWindow.Language_Image_Brasil_Checked.Visibility = System.Windows.Visibility.Visible;
                settingsWindow.Language_Image_Brasil_Rectangle.Stroke = ProjectVariables.MainColor;
            }

        }

        public static void saveSettings()
        {

            if (settingsWindow.Language_Grid_German.Background == ProjectVariables.Theme_DarkRectangleAccent)
            {
                ConfigManager.language = "de-DE";
            }
            else if (settingsWindow.Language_Grid_English.Background == ProjectVariables.Theme_DarkRectangleAccent)
            {
                ConfigManager.language = "en-EN";
            }
            else if (settingsWindow.Language_Grid_Itali.Background == ProjectVariables.Theme_DarkRectangleAccent)
            {
                ConfigManager.language = "it-IT";
            }
            else if (settingsWindow.Language_Grid_French.Background == ProjectVariables.Theme_DarkRectangleAccent)
            {
                ConfigManager.language = "fr-FR";
            }
            else if (settingsWindow.Language_Grid_Spain.Background == ProjectVariables.Theme_DarkRectangleAccent)
            {
                ConfigManager.language = "sp-SP";
            }
            else if (settingsWindow.Language_Grid_Russia.Background == ProjectVariables.Theme_DarkRectangleAccent)
            {
                ConfigManager.language = "ru-RU";
            }
            else if (settingsWindow.Language_Grid_China.Background == ProjectVariables.Theme_DarkRectangleAccent)
            {
                ConfigManager.language = "chn-CHN";
            }
            else if (settingsWindow.Language_Grid_Brasil.Background == ProjectVariables.Theme_DarkRectangleAccent)
            {
                ConfigManager.language = "mex-MEX";
            }
            else if (settingsWindow.Language_Grid_Portugal.Background == ProjectVariables.Theme_DarkRectangleAccent)
            {
                ConfigManager.language = "prt-PRT";
            }
            else if (settingsWindow.Language_Grid_Japan.Background == ProjectVariables.Theme_DarkRectangleAccent)
            {
                ConfigManager.language = "jpn-JPN";
            }

        }
        #endregion

        private void changeLanguage(object sender, MouseButtonEventArgs e)
        {
            for (int i = 0; i < settingsWindow.Language_StackPannel.Children.Count; i++)
            {
                Grid grid = settingsWindow.Language_StackPannel.Children[i] as Grid;
                grid.Background = null;

                Image image = grid.Children[1] as Image;
                image.Visibility = System.Windows.Visibility.Hidden;

                if (grid.Children.Count == 6)
                {
                    Rectangle rectangle = grid.Children[5] as Rectangle;
                    rectangle.Stroke = null;
                }
                else
                {
                    Rectangle rectangle = grid.Children[4] as Rectangle;
                    rectangle.Stroke = null;
                }
            }

            Grid clickedGrid = sender as Grid;
            clickedGrid.Background = ProjectVariables.Theme_DarkRectangleAccent;

            Image changeImage = clickedGrid.Children[1] as Image;
            changeImage.Visibility = System.Windows.Visibility.Visible;

            if (clickedGrid.Children.Count == 6)
            {
                Rectangle rectangle = clickedGrid.Children[5] as Rectangle;
                rectangle.Stroke = ProjectVariables.MainColor;
            }
            else
            {
                Rectangle rectangle = clickedGrid.Children[4] as Rectangle;
                rectangle.Stroke = ProjectVariables.MainColor;
            }

        }

    }
}
