//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWC_VoiceAssistent.projects.db.login.registration {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class German {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal German() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DWC_VoiceAssistent.projects.db.login.registration.German", typeof(German).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ich habe die AGB gelesen und bin damit einverstanden! ähnelt.
        /// </summary>
        internal static string AGB_Agreement {
            get {
                return ResourceManager.GetString("AGB_Agreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registrierung abbrechen ähnelt.
        /// </summary>
        internal static string Cancel_Registration {
            get {
                return ResourceManager.GetString("Cancel_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stadt ähnelt.
        /// </summary>
        internal static string City_Description {
            get {
                return ResourceManager.GetString("City_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Konto erstellen ähnelt.
        /// </summary>
        internal static string Create_Account_Text {
            get {
                return ResourceManager.GetString("Create_Account_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du kannst jetzt ein Konto bei uns erstellen ähnelt.
        /// </summary>
        internal static string CreateAccount_Text {
            get {
                return ResourceManager.GetString("CreateAccount_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deine Email Adresse ähnelt.
        /// </summary>
        internal static string Email_Description {
            get {
                return ResourceManager.GetString("Email_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vor Name ähnelt.
        /// </summary>
        internal static string FirstName_description {
            get {
                return ResourceManager.GetString("FirstName_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nr. ähnelt.
        /// </summary>
        internal static string HouseNumber_Description {
            get {
                return ResourceManager.GetString("HouseNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Land ähnelt.
        /// </summary>
        internal static string Land_Description {
            get {
                return ResourceManager.GetString("Land_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Überleg dir ein sicheres Passwort ähnelt.
        /// </summary>
        internal static string Password_Description {
            get {
                return ResourceManager.GetString("Password_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Überleg dir ein sicheres Passwort ähnelt.
        /// </summary>
        internal static string PasswordEqual_Description {
            get {
                return ResourceManager.GetString("PasswordEqual_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Telefon Nummer ähnelt.
        /// </summary>
        internal static string PhoneNumber_Description {
            get {
                return ResourceManager.GetString("PhoneNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PLZ ähnelt.
        /// </summary>
        internal static string PLZ_Description {
            get {
                return ResourceManager.GetString("PLZ_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nach Name ähnelt.
        /// </summary>
        internal static string SecondName_Description {
            get {
                return ResourceManager.GetString("SecondName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Straße ähnelt.
        /// </summary>
        internal static string Street_Description {
            get {
                return ResourceManager.GetString("Street_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wähle einen einzigartigen Nutzernamen ähnelt.
        /// </summary>
        internal static string UserName_Description {
            get {
                return ResourceManager.GetString("UserName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wir wünschen dir viel Spaß! ähnelt.
        /// </summary>
        internal static string Wish_Text {
            get {
                return ResourceManager.GetString("Wish_Text", resourceCulture);
            }
        }
    }
}
