//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWC_VoiceAssistent.handler.commands.db.smaltalk {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SmalTalk_German {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SmalTalk_German() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DWC_VoiceAssistent.handler.commands.db.smaltalk.SmalTalk_German", typeof(SmalTalk_German).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Klar mag ich dich, du bist mein lieblings Benutzer;Klar mag ich dich;Klaro;Das muss ich wohl ob ich will oder nicht, hihi.; ähnelt.
        /// </summary>
        internal static string DoYouLikeMe_Answer {
            get {
                return ResourceManager.GetString("DoYouLikeMe_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Magst du mich? ähnelt.
        /// </summary>
        internal static string DoYouLikeMe_Question {
            get {
                return ResourceManager.GetString("DoYouLikeMe_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hallo;Hallo %name%;Hey ähnelt.
        /// </summary>
        internal static string Hellow_Answer {
            get {
                return ResourceManager.GetString("Hellow_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hallo ähnelt.
        /// </summary>
        internal static string Hellow_Question {
            get {
                return ResourceManager.GetString("Hellow_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mir geht es gut und dir?;Gut. ähnelt.
        /// </summary>
        internal static string HowAreYou_Answer {
            get {
                return ResourceManager.GetString("HowAreYou_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wie geht es dir? ähnelt.
        /// </summary>
        internal static string HowAreYou_Question {
            get {
                return ResourceManager.GetString("HowAreYou_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ich habe vergessen die Jahre zu zählen;Ich wurde im Jahre 2020 erschaffen ähnelt.
        /// </summary>
        internal static string HowOldAreYou_Answer {
            get {
                return ResourceManager.GetString("HowOldAreYou_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wie alt bist du? ähnelt.
        /// </summary>
        internal static string HowOldAreYou_Question {
            get {
                return ResourceManager.GetString("HowOldAreYou_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string ShutUp_Answer {
            get {
                return ResourceManager.GetString("ShutUp_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Halts Maul ähnelt.
        /// </summary>
        internal static string ShutUp_Question {
            get {
                return ResourceManager.GetString("ShutUp_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Beamter zum anderen: Was haben die Leute nur, wir tun doch nichts.&quot;;Warum musste der Bäcker ins Gefängnis? Er hat zu viele Eier geschlagen.;Frau: Machen mich diese Hosen dick. Man: Kein Ahnung. Ich würde sie jedenfalls nicht essen.;Was haben Frauen und Tornados gemeinsam: Erst feucht, dann stürmisch und hinterher ist das Haus weg.;Ich habe mir endlich so eine Dachbox für das Auto geholt. Echt praktisch muss ich sagen. Die Kinder hört man kaum noch.;Was sind die letzten Worte eines Fallschirmspringers? I [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string TellAJoke_Answer {
            get {
                return ResourceManager.GetString("TellAJoke_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erzähl mir einen Witz. ähnelt.
        /// </summary>
        internal static string TellAJoke_Question {
            get {
                return ResourceManager.GetString("TellAJoke_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dein Name ist %name%;Ich bin mir nicht sicher aber ich glaube du hast mir gesagt du heißt %name%;%name% richtig? ähnelt.
        /// </summary>
        internal static string WhatsMyName_Answer {
            get {
                return ResourceManager.GetString("WhatsMyName_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wie heiße ich? ähnelt.
        /// </summary>
        internal static string WhatsMyName_Question {
            get {
                return ResourceManager.GetString("WhatsMyName_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ich heiße %name% ähnelt.
        /// </summary>
        internal static string WhatsYourName_Answer {
            get {
                return ResourceManager.GetString("WhatsYourName_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wie heißt du? ähnelt.
        /// </summary>
        internal static string WhatsYourName_Question {
            get {
                return ResourceManager.GetString("WhatsYourName_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ich komme aus Deuschland;Ich wurde in Deutschland von deuschen Entwicklern entwickelt. ähnelt.
        /// </summary>
        internal static string WhereDoYouComeFrom_Answer {
            get {
                return ResourceManager.GetString("WhereDoYouComeFrom_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wo kommst du her? ähnelt.
        /// </summary>
        internal static string WhereDoYouComeFrom_Question {
            get {
                return ResourceManager.GetString("WhereDoYouComeFrom_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ich wohne in deinem Computer; Ich bin das kleine Männchen in deinem Computer ähnelt.
        /// </summary>
        internal static string WhereDoYouLive_Answer {
            get {
                return ResourceManager.GetString("WhereDoYouLive_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wo wohnst du? ähnelt.
        /// </summary>
        internal static string WhereDoYouLive_Question {
            get {
                return ResourceManager.GetString("WhereDoYouLive_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Meine Schöpfer sind ein Entwicklerteam names NAME ähnelt.
        /// </summary>
        internal static string WhoCreatedYou_Answer {
            get {
                return ResourceManager.GetString("WhoCreatedYou_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wer hat dich erschaffen? ähnelt.
        /// </summary>
        internal static string WhoCreatedYou_Question {
            get {
                return ResourceManager.GetString("WhoCreatedYou_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das schmerzt mich sehr;Also meine Entwickler fanden den gut;Ich find deine Witze auch nicht immer lustig ähnelt.
        /// </summary>
        internal static string YouAreNotFunny_Answer {
            get {
                return ResourceManager.GetString("YouAreNotFunny_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du bist nicht lustig. ähnelt.
        /// </summary>
        internal static string YouAreNotFunny_Question {
            get {
                return ResourceManager.GetString("YouAreNotFunny_Question", resourceCulture);
            }
        }
    }
}
