//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWC_VoiceAssistent.handler.commands.db.smaltalk {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SmalTalk_English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SmalTalk_English() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DWC_VoiceAssistent.handler.commands.db.smaltalk.SmalTalk_English", typeof(SmalTalk_English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes i do;Yes;I think i have to if I want or not, hihi. ähnelt.
        /// </summary>
        internal static string DoYouLikeMe_Answer {
            get {
                return ResourceManager.GetString("DoYouLikeMe_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you like me? ähnelt.
        /// </summary>
        internal static string DoYouLikeMe_Question {
            get {
                return ResourceManager.GetString("DoYouLikeMe_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hellow;Hey;Hellow %name% ähnelt.
        /// </summary>
        internal static string Hellow_Answer {
            get {
                return ResourceManager.GetString("Hellow_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hellow ähnelt.
        /// </summary>
        internal static string Hellow_Question {
            get {
                return ResourceManager.GetString("Hellow_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I am fine. How are you?;Fine; I&apos;m fine. ähnelt.
        /// </summary>
        internal static string HowAreYou_Answer {
            get {
                return ResourceManager.GetString("HowAreYou_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How are you? ähnelt.
        /// </summary>
        internal static string HowAreYou_Question {
            get {
                return ResourceManager.GetString("HowAreYou_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I forgot to count the Years;I am not exactly sure;I was created in 2020 ähnelt.
        /// </summary>
        internal static string HowOldAreYou_Answer {
            get {
                return ResourceManager.GetString("HowOldAreYou_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How old are you? ähnelt.
        /// </summary>
        internal static string HowOldAreYou_Question {
            get {
                return ResourceManager.GetString("HowOldAreYou_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string ShutUp_Answer {
            get {
                return ResourceManager.GetString("ShutUp_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shut up. ähnelt.
        /// </summary>
        internal static string ShutUp_Question {
            get {
                return ResourceManager.GetString("ShutUp_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string TellAJoke_Answer {
            get {
                return ResourceManager.GetString("TellAJoke_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tell me a Joke. ähnelt.
        /// </summary>
        internal static string TellAJoke_Question {
            get {
                return ResourceManager.GetString("TellAJoke_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your Name is %name%;I think you told me your Name is %name%;%name% right? ähnelt.
        /// </summary>
        internal static string WhatsMyName_Answer {
            get {
                return ResourceManager.GetString("WhatsMyName_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die What&apos;s my Name? ähnelt.
        /// </summary>
        internal static string WhatsMyName_Question {
            get {
                return ResourceManager.GetString("WhatsMyName_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die My Name is %name%. ähnelt.
        /// </summary>
        internal static string WhatsYourName_Answer {
            get {
                return ResourceManager.GetString("WhatsYourName_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die What&apos;s your Name? ähnelt.
        /// </summary>
        internal static string WhatsYourName_Question {
            get {
                return ResourceManager.GetString("WhatsYourName_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I come from Germany;I was created in Germany from german Developers ähnelt.
        /// </summary>
        internal static string WhereDoYouComeFrom_Answer {
            get {
                return ResourceManager.GetString("WhereDoYouComeFrom_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Where do you come from? ähnelt.
        /// </summary>
        internal static string WhereDoYouComeFrom_Question {
            get {
                return ResourceManager.GetString("WhereDoYouComeFrom_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I life in your Computer; I am the tiny little Guy in your Computer ähnelt.
        /// </summary>
        internal static string WhereDoYouLive_Answer {
            get {
                return ResourceManager.GetString("WhereDoYouLive_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Where do you live? ähnelt.
        /// </summary>
        internal static string WhereDoYouLive_Question {
            get {
                return ResourceManager.GetString("WhereDoYouLive_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die My Creatores are a developer Team called NAME ähnelt.
        /// </summary>
        internal static string WhoCreatedYou_Answer {
            get {
                return ResourceManager.GetString("WhoCreatedYou_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Who is your Creator? ähnelt.
        /// </summary>
        internal static string WhoCreatedYou_Question {
            get {
                return ResourceManager.GetString("WhoCreatedYou_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string YouAreNotFunny_Answer {
            get {
                return ResourceManager.GetString("YouAreNotFunny_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You aren&apos;t funny. ähnelt.
        /// </summary>
        internal static string YouAreNotFunny_Question {
            get {
                return ResourceManager.GetString("YouAreNotFunny_Question", resourceCulture);
            }
        }
    }
}
