//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWC_VoiceAssistent.projects.db.pluginstore {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Chinese {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Chinese() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DWC_VoiceAssistent.projects.db.pluginstore.Chinese", typeof(Chinese).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 四处看一下 ähnelt.
        /// </summary>
        internal static string LookAround_Text {
            get {
                return ResourceManager.GetString("LookAround_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 下载 ähnelt.
        /// </summary>
        internal static string PluginAktivityInstallation_Install {
            get {
                return ResourceManager.GetString("PluginAktivityInstallation_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 卸载 ähnelt.
        /// </summary>
        internal static string PluginAktivityInstallation_UnInstall {
            get {
                return ResourceManager.GetString("PluginAktivityInstallation_UnInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 激活的 ähnelt.
        /// </summary>
        internal static string PluginAktivityState_Active {
            get {
                return ResourceManager.GetString("PluginAktivityState_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 无效 ähnelt.
        /// </summary>
        internal static string PluginAktivityState_InActive {
            get {
                return ResourceManager.GetString("PluginAktivityState_InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 應用程式 ähnelt.
        /// </summary>
        internal static string Plugins_Apps {
            get {
                return ResourceManager.GetString("Plugins_Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 榜首 ähnelt.
        /// </summary>
        internal static string Plugins_Charts {
            get {
                return ResourceManager.GetString("Plugins_Charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 为你准备的 ähnelt.
        /// </summary>
        internal static string Plugins_ForYou {
            get {
                return ResourceManager.GetString("Plugins_ForYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 游戏 ähnelt.
        /// </summary>
        internal static string Plugins_Games {
            get {
                return ResourceManager.GetString("Plugins_Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 我们的原创 ähnelt.
        /// </summary>
        internal static string Plugins_Original {
            get {
                return ResourceManager.GetString("Plugins_Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 版本 ähnelt.
        /// </summary>
        internal static string PluginVersion {
            get {
                return ResourceManager.GetString("PluginVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 插件预览 ähnelt.
        /// </summary>
        internal static string PluginView {
            get {
                return ResourceManager.GetString("PluginView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 点按搜索..... ähnelt.
        /// </summary>
        internal static string Search_Text {
            get {
                return ResourceManager.GetString("Search_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 欢迎来到插件商店 ähnelt.
        /// </summary>
        internal static string Welcome_Text {
            get {
                return ResourceManager.GetString("Welcome_Text", resourceCulture);
            }
        }
    }
}
