//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWC_VoiceAssistent.projects.db.pluginstore {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class German {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal German() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DWC_VoiceAssistent.projects.db.pluginstore.German", typeof(German).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schaue dich ein wenig um ähnelt.
        /// </summary>
        internal static string LookAround_Text {
            get {
                return ResourceManager.GetString("LookAround_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Herunterladen ähnelt.
        /// </summary>
        internal static string PluginAktivityInstallation_Install {
            get {
                return ResourceManager.GetString("PluginAktivityInstallation_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deinstallieren ähnelt.
        /// </summary>
        internal static string PluginAktivityInstallation_UnInstall {
            get {
                return ResourceManager.GetString("PluginAktivityInstallation_UnInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktiv ähnelt.
        /// </summary>
        internal static string PluginAktivityState_Active {
            get {
                return ResourceManager.GetString("PluginAktivityState_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inaktiv ähnelt.
        /// </summary>
        internal static string PluginAktivityState_InActive {
            get {
                return ResourceManager.GetString("PluginAktivityState_InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apps ähnelt.
        /// </summary>
        internal static string Plugins_Apps {
            get {
                return ResourceManager.GetString("Plugins_Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Top Charts ähnelt.
        /// </summary>
        internal static string Plugins_Charts {
            get {
                return ResourceManager.GetString("Plugins_Charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Für dich bestimmt ähnelt.
        /// </summary>
        internal static string Plugins_ForYou {
            get {
                return ResourceManager.GetString("Plugins_ForYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spiele ähnelt.
        /// </summary>
        internal static string Plugins_Games {
            get {
                return ResourceManager.GetString("Plugins_Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Original von uns ähnelt.
        /// </summary>
        internal static string Plugins_Original {
            get {
                return ResourceManager.GetString("Plugins_Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version ähnelt.
        /// </summary>
        internal static string PluginVersion {
            get {
                return ResourceManager.GetString("PluginVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugin Vorschau ähnelt.
        /// </summary>
        internal static string PluginView {
            get {
                return ResourceManager.GetString("PluginView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tippe zum suchen ... ähnelt.
        /// </summary>
        internal static string Search_Text {
            get {
                return ResourceManager.GetString("Search_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willkommen im Plugin Store ähnelt.
        /// </summary>
        internal static string Welcome_Text {
            get {
                return ResourceManager.GetString("Welcome_Text", resourceCulture);
            }
        }
    }
}
