//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWC_VoiceAssistent.projects.db.settings {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Chinese {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Chinese() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DWC_VoiceAssistent.projects.db.settings.Chinese", typeof(Chinese).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 你的出生日期 ähnelt.
        /// </summary>
        internal static string Account_Birthday_Text {
            get {
                return ResourceManager.GetString("Account_Birthday_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 更改昵称 ähnelt.
        /// </summary>
        internal static string Account_ChangeNickname {
            get {
                return ResourceManager.GetString("Account_ChangeNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 一年只能换一次昵称! ähnelt.
        /// </summary>
        internal static string Account_ChangeNickname_Info {
            get {
                return ResourceManager.GetString("Account_ChangeNickname_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 城市 ähnelt.
        /// </summary>
        internal static string Account_City_Text {
            get {
                return ResourceManager.GetString("Account_City_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 你的国家 ähnelt.
        /// </summary>
        internal static string Account_Cuntry_Text {
            get {
                return ResourceManager.GetString("Account_Cuntry_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 没有人能看到你的真实姓名和地址等个人信息。只显示您的昵称，您的个人资料图片和活动状态的选项 ähnelt.
        /// </summary>
        internal static string Account_DataInfo_Text {
            get {
                return ResourceManager.GetString("Account_DataInfo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 编辑地址数据 ähnelt.
        /// </summary>
        internal static string Account_EditAddress {
            get {
                return ResourceManager.GetString("Account_EditAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 编辑个人数据 ähnelt.
        /// </summary>
        internal static string Account_EditPersonalData {
            get {
                return ResourceManager.GetString("Account_EditPersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 替换个人资料图片 ähnelt.
        /// </summary>
        internal static string Account_EditProfilePicture {
            get {
                return ResourceManager.GetString("Account_EditProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 电子邮件 ähnelt.
        /// </summary>
        internal static string Account_Email_Text {
            get {
                return ResourceManager.GetString("Account_Email_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 你的名字 ähnelt.
        /// </summary>
        internal static string Account_FirstName_Text {
            get {
                return ResourceManager.GetString("Account_FirstName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 你的性别 ähnelt.
        /// </summary>
        internal static string Account_Gender_Text {
            get {
                return ResourceManager.GetString("Account_Gender_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 房号 ähnelt.
        /// </summary>
        internal static string Account_HouseNumber_Text {
            get {
                return ResourceManager.GetString("Account_HouseNumber_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 没有人能看到你的真实姓名和地址等个人信息。只显示您的昵称、个人资料图片和活动状态。                                                                                                                            
        ///要编辑你的昵称和你的公开资料，请转到%path%。 ähnelt.
        /// </summary>
        internal static string Account_InfoText {
            get {
                return ResourceManager.GetString("Account_InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 你已经是我们的一员了 ähnelt.
        /// </summary>
        internal static string Account_PartOfUs_Text {
            get {
                return ResourceManager.GetString("Account_PartOfUs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 您的个人数据 ähnelt.
        /// </summary>
        internal static string Account_PersonalData_Text {
            get {
                return ResourceManager.GetString("Account_PersonalData_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 电话号 ähnelt.
        /// </summary>
        internal static string Account_PhoneNumber_Text {
            get {
                return ResourceManager.GetString("Account_PhoneNumber_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 郵遞區號 ähnelt.
        /// </summary>
        internal static string Account_PLZ_Text {
            get {
                return ResourceManager.GetString("Account_PLZ_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 重置个人资料图片 ähnelt.
        /// </summary>
        internal static string Account_ResetProfilePicture {
            get {
                return ResourceManager.GetString("Account_ResetProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 你的姓 ähnelt.
        /// </summary>
        internal static string Account_SecondName_Text {
            get {
                return ResourceManager.GetString("Account_SecondName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 街道 ähnelt.
        /// </summary>
        internal static string Account_Street_Text {
            get {
                return ResourceManager.GetString("Account_Street_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 添加账户 ähnelt.
        /// </summary>
        internal static string ButtonText_AddAcount {
            get {
                return ResourceManager.GetString("ButtonText_AddAcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 变化 ähnelt.
        /// </summary>
        internal static string ButtonText_Change {
            get {
                return ResourceManager.GetString("ButtonText_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 显示 ähnelt.
        /// </summary>
        internal static string ButtonText_Show {
            get {
                return ResourceManager.GetString("ButtonText_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 当您启动电脑时，应用程序会自动启动。 ähnelt.
        /// </summary>
        internal static string ClientStart_Autostart {
            get {
                return ResourceManager.GetString("ClientStart_Autostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 应用启动 ähnelt.
        /// </summary>
        internal static string ClientStart_Heading {
            get {
                return ResourceManager.GetString("ClientStart_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 开始应用最小化 ähnelt.
        /// </summary>
        internal static string ClientStart_MinimizedStart {
            get {
                return ResourceManager.GetString("ClientStart_MinimizedStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 增加邮件账户、社交媒体和游戏服务 ähnelt.
        /// </summary>
        internal static string ConnectedAccounts_AddAccountInfo {
            get {
                return ResourceManager.GetString("ConnectedAccounts_AddAccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 添加其他服务的账户。这将使您可以在一个程序中使用外部服务并管理它们。 ähnelt.
        /// </summary>
        internal static string ConnectedAccounts_AddAccounts_Info {
            get {
                return ResourceManager.GetString("ConnectedAccounts_AddAccounts_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 添加一个新账户 ähnelt.
        /// </summary>
        internal static string ConnectedAccounts_AddNewAccount {
            get {
                return ResourceManager.GetString("ConnectedAccounts_AddNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 相关账户 ähnelt.
        /// </summary>
        internal static string ConnectedAccounts_ConnectedAccounts {
            get {
                return ResourceManager.GetString("ConnectedAccounts_ConnectedAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 已连接的电子邮件账户 ähnelt.
        /// </summary>
        internal static string ConnectedAccounts_ConnectedMainEmail {
            get {
                return ResourceManager.GetString("ConnectedAccounts_ConnectedMainEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 你的连接电子邮件账户具有最高优先级。无论谁有这个账户的访问权限，也可以访问其他 账户。 ähnelt.
        /// </summary>
        internal static string ConnectedAccounts_MainEmail_Info {
            get {
                return ResourceManager.GetString("ConnectedAccounts_MainEmail_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 让自己被这个设计所迷惑 ähnelt.
        /// </summary>
        internal static string Design_BrightDesign_Content {
            get {
                return ResourceManager.GetString("Design_BrightDesign_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 明亮的设计 ähnelt.
        /// </summary>
        internal static string Design_BrightDesign_Heading {
            get {
                return ResourceManager.GetString("Design_BrightDesign_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 选择你自己的颜色 ähnelt.
        /// </summary>
        internal static string Design_Color_Custom_Description {
            get {
                return ResourceManager.GetString("Design_Color_Custom_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 自己的颜色 ähnelt.
        /// </summary>
        internal static string Design_Color_Custom_Heading {
            get {
                return ResourceManager.GetString("Design_Color_Custom_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 美丽的蓝色 ähnelt.
        /// </summary>
        internal static string Design_Color_Default_Description {
            get {
                return ResourceManager.GetString("Design_Color_Default_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 标准蓝 ähnelt.
        /// </summary>
        internal static string Design_Color_Default_Heading {
            get {
                return ResourceManager.GetString("Design_Color_Default_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 所选颜色用于某些表面、按钮和文本字段。 ähnelt.
        /// </summary>
        internal static string Design_Color_Description {
            get {
                return ResourceManager.GetString("Design_Color_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 颜色方案 ähnelt.
        /// </summary>
        internal static string Design_Color_Heading {
            get {
                return ResourceManager.GetString("Design_Color_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 美丽宜人的暗色设计 ähnelt.
        /// </summary>
        internal static string Design_DarkDesign_Content {
            get {
                return ResourceManager.GetString("Design_DarkDesign_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 深色设计 ähnelt.
        /// </summary>
        internal static string Design_DarkDesign_Heading {
            get {
                return ResourceManager.GetString("Design_DarkDesign_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 你想用哪种设计？ ähnelt.
        /// </summary>
        internal static string Design_Description {
            get {
                return ResourceManager.GetString("Design_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 载入或创建一个自定义字体（.ttf文件），在这个文件上点击两次，然后点击安装。那么你可以在这里选择并使用它 ähnelt.
        /// </summary>
        internal static string Design_Font_Custom_Description {
            get {
                return ResourceManager.GetString("Design_Font_Custom_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 自己的字体 ähnelt.
        /// </summary>
        internal static string Design_Font_Custom_Heading {
            get {
                return ResourceManager.GetString("Design_Font_Custom_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 标准字体 ähnelt.
        /// </summary>
        internal static string Design_Font_Default_Heading {
            get {
                return ResourceManager.GetString("Design_Font_Default_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 我们使用这种字体显示的大部分内容。 ähnelt.
        /// </summary>
        internal static string Design_Font_Description {
            get {
                return ResourceManager.GetString("Design_Font_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 使用的字体 ähnelt.
        /// </summary>
        internal static string Design_Font_Heading {
            get {
                return ResourceManager.GetString("Design_Font_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 设计 ähnelt.
        /// </summary>
        internal static string Design_OwnBackgrouond {
            get {
                return ResourceManager.GetString("Design_OwnBackgrouond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 评估并发送背景图 ähnelt.
        /// </summary>
        internal static string Design_RatingBackground {
            get {
                return ResourceManager.GetString("Design_RatingBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 我们用这个设置来关闭对象 ähnelt.
        /// </summary>
        internal static string Design_Rounding_Description {
            get {
                return ResourceManager.GetString("Design_Rounding_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 四舍五入 ähnelt.
        /// </summary>
        internal static string Design_Rounding_Heading {
            get {
                return ResourceManager.GetString("Design_Rounding_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 最大四舍五入 ähnelt.
        /// </summary>
        internal static string Design_Rounding_MaximalRounding {
            get {
                return ResourceManager.GetString("Design_Rounding_MaximalRounding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 标准光曲线 ähnelt.
        /// </summary>
        internal static string Design_Rounding_MinimalRounding {
            get {
                return ResourceManager.GetString("Design_Rounding_MinimalRounding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 无四舍五入 ähnelt.
        /// </summary>
        internal static string Design_Rounding_NoRounding {
            get {
                return ResourceManager.GetString("Design_Rounding_NoRounding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 阴影赋予表面和物体以深度 ähnelt.
        /// </summary>
        internal static string Design_Shaddow_Description {
            get {
                return ResourceManager.GetString("Design_Shaddow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 赋予物体以阴影 ähnelt.
        /// </summary>
        internal static string Design_Shaddow_Heading {
            get {
                return ResourceManager.GetString("Design_Shaddow_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 透明、美观，保证独一无二 ähnelt.
        /// </summary>
        internal static string Design_TransparentDesign_Content {
            get {
                return ResourceManager.GetString("Design_TransparentDesign_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 透明设计 ähnelt.
        /// </summary>
        internal static string Design_TransparentDesign_Heading {
            get {
                return ResourceManager.GetString("Design_TransparentDesign_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 艺术设计 ähnelt.
        /// </summary>
        internal static string Design_TransparentDesignImage_Art {
            get {
                return ResourceManager.GetString("Design_TransparentDesignImage_Art", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 城市设计 ähnelt.
        /// </summary>
        internal static string Design_TransparentDesignImage_City {
            get {
                return ResourceManager.GetString("Design_TransparentDesignImage_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 定制设计 ähnelt.
        /// </summary>
        internal static string Design_TransparentDesignImage_Custom {
            get {
                return ResourceManager.GetString("Design_TransparentDesignImage_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 默认情况下，背景是预先定义的，你可以从中选择。但你也可以添加自己的背景。最好使用至少全高清分辨率的图片，以获得良好的前景对比度。 ähnelt.
        /// </summary>
        internal static string Design_TransparentDesignImage_Description {
            get {
                return ResourceManager.GetString("Design_TransparentDesignImage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 游戏设计 ähnelt.
        /// </summary>
        internal static string Design_TransparentDesignImage_Gaming {
            get {
                return ResourceManager.GetString("Design_TransparentDesignImage_Gaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 透明的设计 ähnelt.
        /// </summary>
        internal static string Design_TransparentDesignImage_Heading {
            get {
                return ResourceManager.GetString("Design_TransparentDesignImage_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 景观设计 ähnelt.
        /// </summary>
        internal static string Design_TransparentDesignImage_Landscape {
            get {
                return ResourceManager.GetString("Design_TransparentDesignImage_Landscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 当前设备 ähnelt.
        /// </summary>
        internal static string Devices_ConnectedDevicesButton_CurrentDevice {
            get {
                return ResourceManager.GetString("Devices_ConnectedDevicesButton_CurrentDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 连接到您的账户的设备 ähnelt.
        /// </summary>
        internal static string Devices_ConnectedDevicesHeading {
            get {
                return ResourceManager.GetString("Devices_ConnectedDevicesHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 如果设备似乎不熟悉，请单击 &quot;查看 &quot;并从您的帐户中删除设备。 ähnelt.
        /// </summary>
        internal static string Devices_ConnectedDevicesInfo {
            get {
                return ResourceManager.GetString("Devices_ConnectedDevicesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 您的账户 ähnelt.
        /// </summary>
        internal static string DWC_Menu_Account_Text {
            get {
                return ResourceManager.GetString("DWC_Menu_Account_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 相关账户 ähnelt.
        /// </summary>
        internal static string DWC_Menu_ConnectedAccount_Text {
            get {
                return ResourceManager.GetString("DWC_Menu_ConnectedAccount_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Design ähnelt.
        /// </summary>
        internal static string DWC_Menu_Design_Text {
            get {
                return ResourceManager.GetString("DWC_Menu_Design_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 连接设备 ähnelt.
        /// </summary>
        internal static string DWC_Menu_Devices_Text {
            get {
                return ResourceManager.GetString("DWC_Menu_Devices_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 开发者模式 ähnelt.
        /// </summary>
        internal static string DWC_Menu_EditorsMode_Text {
            get {
                return ResourceManager.GetString("DWC_Menu_EditorsMode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 热键 ähnelt.
        /// </summary>
        internal static string DWC_Menu_HotKeys_Text {
            get {
                return ResourceManager.GetString("DWC_Menu_HotKeys_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 游戏内叠加 ähnelt.
        /// </summary>
        internal static string DWC_Menu_InGameOverlay_Text {
            get {
                return ResourceManager.GetString("DWC_Menu_InGameOverlay_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 语系 ähnelt.
        /// </summary>
        internal static string DWC_Menu_Language_Text {
            get {
                return ResourceManager.GetString("DWC_Menu_Language_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 通知书 ähnelt.
        /// </summary>
        internal static string DWC_Menu_Messages_Text {
            get {
                return ResourceManager.GetString("DWC_Menu_Messages_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 付款方式 ähnelt.
        /// </summary>
        internal static string DWC_Menu_PaymentMethodes_Text {
            get {
                return ResourceManager.GetString("DWC_Menu_PaymentMethodes_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 隐私政策 ähnelt.
        /// </summary>
        internal static string DWC_Menu_Privacy_Text {
            get {
                return ResourceManager.GetString("DWC_Menu_Privacy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 应用功能。 ähnelt.
        /// </summary>
        internal static string DWC_Menu_ProgrammFunctions_Text {
            get {
                return ResourceManager.GetString("DWC_Menu_ProgrammFunctions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 应用启动 ähnelt.
        /// </summary>
        internal static string DWC_Menu_ProgrammStart_Text {
            get {
                return ResourceManager.GetString("DWC_Menu_ProgrammStart_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 用户界面 ähnelt.
        /// </summary>
        internal static string DWC_Menu_ProgrammView_Text {
            get {
                return ResourceManager.GetString("DWC_Menu_ProgrammView_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 安全性 ähnelt.
        /// </summary>
        internal static string DWC_Menu_Security_Text {
            get {
                return ResourceManager.GetString("DWC_Menu_Security_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 更新 ähnelt.
        /// </summary>
        internal static string DWC_Menu_Updates_Text {
            get {
                return ResourceManager.GetString("DWC_Menu_Updates_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 用户模式 ähnelt.
        /// </summary>
        internal static string DWC_Menu_UserMode_Text {
            get {
                return ResourceManager.GetString("DWC_Menu_UserMode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 麦克风和视频 ähnelt.
        /// </summary>
        internal static string DWC_Menu_VideoAndAudio_Text {
            get {
                return ResourceManager.GetString("DWC_Menu_VideoAndAudio_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 您的付款方式 ähnelt.
        /// </summary>
        internal static string DWC_Menu_YourPaments_Text {
            get {
                return ResourceManager.GetString("DWC_Menu_YourPaments_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 成人 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Age_Selection_Adult {
            get {
                return ResourceManager.GetString("DWC_Settings_Age_Selection_Adult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 儿童 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Age_Selection_Child {
            get {
                return ResourceManager.GetString("DWC_Settings_Age_Selection_Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 仅限验证过的用户 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Button_OnlyVerifyUsers {
            get {
                return ResourceManager.GetString("DWC_Settings_Button_OnlyVerifyUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 激活的 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Buttons_Active {
            get {
                return ResourceManager.GetString("DWC_Settings_Buttons_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 大家好 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Buttons_EveryOne {
            get {
                return ResourceManager.GetString("DWC_Settings_Buttons_EveryOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 残障人士 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Buttons_InActive {
            get {
                return ResourceManager.GetString("DWC_Settings_Buttons_InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 只有朋友 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Buttons_OnlyFriends {
            get {
                return ResourceManager.GetString("DWC_Settings_Buttons_OnlyFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 颜色选择 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_Color {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 路径 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_Design_BackgroundImage_Path {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_Design_BackgroundImage_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 墙纸 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_Design_BackgroundImage_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_Design_BackgroundImage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 自动启动 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_Generell_AutoStart_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_Generell_AutoStart_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 尽量减少关闭时的窗口 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_Generell_KeepWindowAlife_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_Generell_KeepWindowAlife_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 通知书 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_Generell_Message_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_Generell_Message_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 圆形设计 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_Generell_RoundedDesighn_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_Generell_RoundedDesighn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 欢迎致辞 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_Generell_WelcomeMessage_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_Generell_WelcomeMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 系统设置 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_System {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 语系 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_System_Language_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_System_Language_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 语音回复命令 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_System_ListenName_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_System_ListenName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 用户名称 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_System_UserName_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_System_UserName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 主题选择 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_Theme {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 语音选项 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_Voice {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_Voice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 年龄 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_Voice_Age_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_Voice_Age_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 性别问题 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_Voice_Gender_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_Voice_Gender_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 体积 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Chapter_Voice_Volum_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_Chapter_Voice_Volum_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 相关账户 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Accounts {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 语文助理 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Assistent {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Assistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 外观 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Desighn {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Desighn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 隐私政策 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Eula {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Eula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 延长线 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Extention {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Extention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 朋友设置 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Friends {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 设置 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Heading {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 按钮组合 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_HotKey {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_HotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 语系 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Language {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 登出 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Logout {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 音频 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Microphone {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Microphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 隐私设置 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Privacy {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 申请书 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Program {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 重置 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Reset {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 安全性 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Menu_Security {
            get {
                return ResourceManager.GetString("DWC_Settings_Menu_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 保存设置 ähnelt.
        /// </summary>
        internal static string DWC_Settings_SaveButton_Save_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_SaveButton_Save_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 并关闭(逃逸) ähnelt.
        /// </summary>
        internal static string DWC_Settings_SaveButton_SaveDescription_Text {
            get {
                return ResourceManager.GetString("DWC_Settings_SaveButton_SaveDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 您的设置已成功应用 ähnelt.
        /// </summary>
        internal static string DWC_Settings_SaveMessage {
            get {
                return ResourceManager.GetString("DWC_Settings_SaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DarkWolfCraft - 设置 ähnelt.
        /// </summary>
        internal static string DWC_Settings_SaveMessageHeading {
            get {
                return ResourceManager.GetString("DWC_Settings_SaveMessageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 女士 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Voice_Selection_Female {
            get {
                return ResourceManager.GetString("DWC_Settings_Voice_Selection_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 人 ähnelt.
        /// </summary>
        internal static string DWC_Settings_Voice_Selection_Male {
            get {
                return ResourceManager.GetString("DWC_Settings_Voice_Selection_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 有人喜欢比较详细，也有人喜欢简单。你的选择对程序的功能没有任何影响。根据这一点，我们会给出额外的信息或定制选项! ähnelt.
        /// </summary>
        internal static string EditorsMode_Description {
            get {
                return ResourceManager.GetString("EditorsMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 你是开发商？我们将向您展示更多的信息，并为您提供更多的服务发展情况。让自己受到启发，帮助我们发现安全漏洞和BUG。 ähnelt.
        /// </summary>
        internal static string EditorsMode_DeveloperMode_Description {
            get {
                return ResourceManager.GetString("EditorsMode_DeveloperMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 开发商时尚 ähnelt.
        /// </summary>
        internal static string EditorsMode_DeveloperMode_Heading {
            get {
                return ResourceManager.GetString("EditorsMode_DeveloperMode_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 在设计和界面设计方面，你有先进的功能。定制程序，让你的创意自由发挥。 ähnelt.
        /// </summary>
        internal static string EditorsMode_EditorsMode_Description {
            get {
                return ResourceManager.GetString("EditorsMode_EditorsMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 编辑模式 ähnelt.
        /// </summary>
        internal static string EditorsMode_EditorsMode_Heading {
            get {
                return ResourceManager.GetString("EditorsMode_EditorsMode_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 用户模式 ähnelt.
        /// </summary>
        internal static string EditorsMode_Heading {
            get {
                return ResourceManager.GetString("EditorsMode_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 我们尽量取悦所有用户，即使他们的兴趣爱好完全不同，我们也会尽量取悦他们。通过我们的优化模块，我们尽量为每一个用户量身定制最优质的服务。您提供的信息越多，我们就能更好地对您的兴趣进行分类! ähnelt.
        /// </summary>
        internal static string EditorsMode_InfoDescription {
            get {
                return ResourceManager.GetString("EditorsMode_InfoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 适应性 ähnelt.
        /// </summary>
        internal static string EditorsMode_InfoHeading {
            get {
                return ResourceManager.GetString("EditorsMode_InfoHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 你可以期待所有的功能都是完整的，我们在设计和界面设计方面为你做了大部分的工作，你不用担心。 ähnelt.
        /// </summary>
        internal static string EditorsMode_NormalMode_Description {
            get {
                return ResourceManager.GetString("EditorsMode_NormalMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 普通模式 ähnelt.
        /// </summary>
        internal static string EditorsMode_NormalMode_Heading {
            get {
                return ResourceManager.GetString("EditorsMode_NormalMode_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 创建一个新的热键 ähnelt.
        /// </summary>
        internal static string HotKeys_CreateNewHotKey {
            get {
                return ResourceManager.GetString("HotKeys_CreateNewHotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 禁用所有热键 ähnelt.
        /// </summary>
        internal static string HotKeys_EnableAllHotkeys {
            get {
                return ResourceManager.GetString("HotKeys_EnableAllHotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 禁用所有热键 ähnelt.
        /// </summary>
        internal static string HotKeys_EnableOwnHotkeys {
            get {
                return ResourceManager.GetString("HotKeys_EnableOwnHotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 热键 ähnelt.
        /// </summary>
        internal static string HotKeys_Heading {
            get {
                return ResourceManager.GetString("HotKeys_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 要更改热键，请按组合键并输入新的组合键。按ESC键取消操作。 ähnelt.
        /// </summary>
        internal static string HotKeys_Info {
            get {
                return ResourceManager.GetString("HotKeys_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 激活/停用musicbot ähnelt.
        /// </summary>
        internal static string HotKeys_Option_Musikbot {
            get {
                return ResourceManager.GetString("HotKeys_Option_Musikbot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 静音开/关 ähnelt.
        /// </summary>
        internal static string HotKeys_Option_Mute {
            get {
                return ResourceManager.GetString("HotKeys_Option_Mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 推入式对话 ähnelt.
        /// </summary>
        internal static string HotKeys_Option_PushToTalk {
            get {
                return ResourceManager.GetString("HotKeys_Option_PushToTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 触发器语音助手 ähnelt.
        /// </summary>
        internal static string HotKeys_Option_VoiceAssistent {
            get {
                return ResourceManager.GetString("HotKeys_Option_VoiceAssistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 重置所有热键 ähnelt.
        /// </summary>
        internal static string HotKeys_ResetAllHotKeys {
            get {
                return ResourceManager.GetString("HotKeys_ResetAllHotKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 在游戏覆盖中激活 ähnelt.
        /// </summary>
        internal static string InGameOverlay_AktivateIngameOverlay {
            get {
                return ResourceManager.GetString("InGameOverlay_AktivateIngameOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 准备好一起玩了吗？ ähnelt.
        /// </summary>
        internal static string InGameOverlay_Description {
            get {
                return ResourceManager.GetString("InGameOverlay_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 游戏内叠加 ähnelt.
        /// </summary>
        internal static string InGameOverlay_Heading {
            get {
                return ResourceManager.GetString("InGameOverlay_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 叠加在某一点上显示的是 ähnelt.
        /// </summary>
        internal static string InGameOverlay_Show_Heading {
            get {
                return ResourceManager.GetString("InGameOverlay_Show_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 音乐机器人会显示，你可以看到你正在听哪一首歌。 ähnelt.
        /// </summary>
        internal static string InGameOverlay_ShowMusik_Content {
            get {
                return ResourceManager.GetString("InGameOverlay_ShowMusik_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 显示musicbot ähnelt.
        /// </summary>
        internal static string InGameOverlay_ShowMusik_Heading {
            get {
                return ResourceManager.GetString("InGameOverlay_ShowMusik_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 如果激活了这个功能，你只能看到其他的名字。 ähnelt.
        /// </summary>
        internal static string InGameOverlay_ShowProfilePicture_Content {
            get {
                return ResourceManager.GetString("InGameOverlay_ShowProfilePicture_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 隐藏个人资料图片 ähnelt.
        /// </summary>
        internal static string InGameOverlay_ShowProfilePicture_Heading {
            get {
                return ResourceManager.GetString("InGameOverlay_ShowProfilePicture_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 如果激活了这个功能，当没有人说话时，覆盖层就会被隐藏。 ähnelt.
        /// </summary>
        internal static string InGameOverlay_ShowWhileTalking_Content {
            get {
                return ResourceManager.GetString("InGameOverlay_ShowWhileTalking_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 只有当有人说话时才显示叠加 ähnelt.
        /// </summary>
        internal static string InGameOverlay_ShowWhileTalking_Heading {
            get {
                return ResourceManager.GetString("InGameOverlay_ShowWhileTalking_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 选择你自己的背景 ähnelt.
        /// </summary>
        internal static string Landschaft_Design {
            get {
                return ResourceManager.GetString("Landschaft Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (自动生成) ähnelt.
        /// </summary>
        internal static string Language_AutogeneratedInfo {
            get {
                return ResourceManager.GetString("Language_AutogeneratedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 选择你的语言! 请注意，有些语言是自动翻译完成的，我们不能保证也不承担任何责任。我们很快就会提供多种语言的综合翻译。如果您当地语言不通 
        ///你可以帮我们做一个翻译样本! 了解更多 ähnelt.
        /// </summary>
        internal static string Language_Description {
            get {
                return ResourceManager.GetString("Language_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 您的语言 ähnelt.
        /// </summary>
        internal static string Language_Heading {
            get {
                return ResourceManager.GetString("Language_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 如果您启用了这个功能，如果我们无法检测到麦克风，即使您正在说话，或者您的声音被切断，我们也会通知您。 ähnelt.
        /// </summary>
        internal static string Microphone_AudioHelp_Description {
            get {
                return ResourceManager.GetString("Microphone_AudioHelp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 音频帮助 ähnelt.
        /// </summary>
        internal static string Microphone_AudioHelp_Heading {
            get {
                return ResourceManager.GetString("Microphone_AudioHelp_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 背景噪音和杂音被压制，提供了良好的音频质量。 ähnelt.
        /// </summary>
        internal static string Microphone_AudioOptimisation_Content {
            get {
                return ResourceManager.GetString("Microphone_AudioOptimisation_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 音频优化软件 ähnelt.
        /// </summary>
        internal static string Microphone_AudioOptimisation_Heading {
            get {
                return ResourceManager.GetString("Microphone_AudioOptimisation_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 你看上面，当你的麦克风被激活时 ähnelt.
        /// </summary>
        internal static string Microphone_AutomaticVoiceDetection_Description {
            get {
                return ResourceManager.GetString("Microphone_AutomaticVoiceDetection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 自动确定麦克风的灵敏度 ähnelt.
        /// </summary>
        internal static string Microphone_AutomaticVoiceDetection_Heading {
            get {
                return ResourceManager.GetString("Microphone_AutomaticVoiceDetection_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 话筒启动 ähnelt.
        /// </summary>
        internal static string Microphone_Heading {
            get {
                return ResourceManager.GetString("Microphone_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 发言人（姓名） ähnelt.
        /// </summary>
        internal static string Microphone_HeadsetName {
            get {
                return ResourceManager.GetString("Microphone_HeadsetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 输入量 ähnelt.
        /// </summary>
        internal static string Microphone_InputText {
            get {
                return ResourceManager.GetString("Microphone_InputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 麦克风（名称） ähnelt.
        /// </summary>
        internal static string Microphone_MicrophoneName {
            get {
                return ResourceManager.GetString("Microphone_MicrophoneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 输出量 ähnelt.
        /// </summary>
        internal static string Microphone_OutputText {
            get {
                return ResourceManager.GetString("Microphone_OutputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 如果语音激活被停用，请使用 &quot;推送通话&quot;（可在热键下编辑）。 ähnelt.
        /// </summary>
        internal static string Microphone_VoiceActivation_Description {
            get {
                return ResourceManager.GetString("Microphone_VoiceActivation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 语音激活 ähnelt.
        /// </summary>
        internal static string Microphone_VoiceActivation_Heading {
            get {
                return ResourceManager.GetString("Microphone_VoiceActivation_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 我们应该显示哪些通知 ähnelt.
        /// </summary>
        internal static string Notification_Description {
            get {
                return ResourceManager.GetString("Notification_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 通过桌面的安全通知是很重要的，如果情况紧急，有人试图访问您的账户，例如 ähnelt.
        /// </summary>
        internal static string Notification_DescropSecurityNotification_Description {
            get {
                return ResourceManager.GetString("Notification_DescropSecurityNotification_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 桌面安全通知 ähnelt.
        /// </summary>
        internal static string Notification_DescropSecurityNotification_Heading {
            get {
                return ResourceManager.GetString("Notification_DescropSecurityNotification_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 如果您禁用此功能，您将不会收到任何通知! ähnelt.
        /// </summary>
        internal static string Notification_DesktopNotification_Description {
            get {
                return ResourceManager.GetString("Notification_DesktopNotification_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 桌面通知 ähnelt.
        /// </summary>
        internal static string Notification_DesktopNotification_Heading {
            get {
                return ResourceManager.GetString("Notification_DesktopNotification_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 您将随时收到关于账户安全、付款确认和其他重要事项的邮件！您将会收到关于账户安全、付款确认和其他重要事项的邮件 ähnelt.
        /// </summary>
        internal static string Notification_EmailNotification_Description {
            get {
                return ResourceManager.GetString("Notification_EmailNotification_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 电子邮件通知 ähnelt.
        /// </summary>
        internal static string Notification_EmailNotification_Heading {
            get {
                return ResourceManager.GetString("Notification_EmailNotification_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 如果有特殊情况，我们会通知您 ähnelt.
        /// </summary>
        internal static string Notification_EmailNotification_PrimeEmail_Description {
            get {
                return ResourceManager.GetString("Notification_EmailNotification_PrimeEmail_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 关于Premium和特别优惠的电子邮件 ähnelt.
        /// </summary>
        internal static string Notification_EmailNotification_PrimeEmail_Heading {
            get {
                return ResourceManager.GetString("Notification_EmailNotification_PrimeEmail_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 当有基于您的游戏和应用程序可用时，我们会通知您。
        ///愿望清单是 ähnelt.
        /// </summary>
        internal static string Notification_EmailNotification_ShopCardEmail_Description {
            get {
                return ResourceManager.GetString("Notification_EmailNotification_ShopCardEmail_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 发送邮件到我的愿望清单 ähnelt.
        /// </summary>
        internal static string Notification_EmailNotification_ShopCardEmail_Heading {
            get {
                return ResourceManager.GetString("Notification_EmailNotification_ShopCardEmail_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 我们为您提供您可能会喜欢的新应用和游戏的信息。 ähnelt.
        /// </summary>
        internal static string Notification_EmailNotification_StoreEmail_Description {
            get {
                return ResourceManager.GetString("Notification_EmailNotification_StoreEmail_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 关于商店内容和优惠的电子邮件 ähnelt.
        /// </summary>
        internal static string Notification_EmailNotification_StoreEmail_Heading {
            get {
                return ResourceManager.GetString("Notification_EmailNotification_StoreEmail_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 关于更新的电子邮件 ähnelt.
        /// </summary>
        internal static string Notification_EmailNotification_UpdateEmail_Heading {
            get {
                return ResourceManager.GetString("Notification_EmailNotification_UpdateEmail_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 通知书 ähnelt.
        /// </summary>
        internal static string Notification_Heading {
            get {
                return ResourceManager.GetString("Notification_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 当朋友在线时显示 ähnelt.
        /// </summary>
        internal static string Notification_ShowFriendOnline_Heading {
            get {
                return ResourceManager.GetString("Notification_ShowFriendOnline_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 看谁给你写信。您可以将单个联系人和组别静音 ähnelt.
        /// </summary>
        internal static string Notification_ShowTextNotification_Description {
            get {
                return ResourceManager.GetString("Notification_ShowTextNotification_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 显示文本信息 ähnelt.
        /// </summary>
        internal static string Notification_ShowTextNotification_Heading {
            get {
                return ResourceManager.GetString("Notification_ShowTextNotification_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 如果有任何问题，我们会通知您。 ähnelt.
        /// </summary>
        internal static string Notification_SystemNotification_Description {
            get {
                return ResourceManager.GetString("Notification_SystemNotification_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 系统通知 ähnelt.
        /// </summary>
        internal static string Notification_SystemNotification_Heading {
            get {
                return ResourceManager.GetString("Notification_SystemNotification_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 添加支付方式 ähnelt.
        /// </summary>
        internal static string Payments_AddPayment {
            get {
                return ResourceManager.GetString("Payments_AddPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 添加一个账户，只需一键即可轻松安全地进行全平台支付。通过支付方式追踪您的消费，即时取消订阅并轻松获得退款。 ähnelt.
        /// </summary>
        internal static string Payments_Payments_Info {
            get {
                return ResourceManager.GetString("Payments_Payments_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 您在我们这里的账户和付款 ähnelt.
        /// </summary>
        internal static string Payments_Payments_InfoHeading {
            get {
                return ResourceManager.GetString("Payments_Payments_InfoHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 使用快捷支付，能够更快的支付 ähnelt.
        /// </summary>
        internal static string Payments_QuickPay_Description {
            get {
                return ResourceManager.GetString("Payments_QuickPay_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 快速付款 ähnelt.
        /// </summary>
        internal static string Payments_QuickPay_Heading {
            get {
                return ResourceManager.GetString("Payments_QuickPay_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 激活快速支付后，您可以用您喜欢的付款方式自动付款，并跳过确认过程。 ähnelt.
        /// </summary>
        internal static string Payments_QuickPay_QuickPayContent {
            get {
                return ResourceManager.GetString("Payments_QuickPay_QuickPayContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 激活快速支付 ähnelt.
        /// </summary>
        internal static string Payments_QuickPay_QuickPayHeading {
            get {
                return ResourceManager.GetString("Payments_QuickPay_QuickPayHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 激活安全支付 ähnelt.
        /// </summary>
        internal static string Payments_SecurePay_Content {
            get {
                return ResourceManager.GetString("Payments_SecurePay_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 在订购过程中，我们会在订购前申请您的账户密码，以防止未经授权的订单。 ähnelt.
        /// </summary>
        internal static string Payments_SecurePay_Description {
            get {
                return ResourceManager.GetString("Payments_SecurePay_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 安全支付 ähnelt.
        /// </summary>
        internal static string Payments_SecurePay_Heading {
            get {
                return ResourceManager.GetString("Payments_SecurePay_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 您的付款方式 ähnelt.
        /// </summary>
        internal static string Payments_YourPayments {
            get {
                return ResourceManager.GetString("Payments_YourPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 大家好 ähnelt.
        /// </summary>
        internal static string Privacy_Chat_AddFriendPermission_Everybody_Label {
            get {
                return ResourceManager.GetString("Privacy_Chat_AddFriendPermission_Everybody_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 朋友们的朋友 ähnelt.
        /// </summary>
        internal static string Privacy_Chat_AddFriendPermission_Friends_Label {
            get {
                return ResourceManager.GetString("Privacy_Chat_AddFriendPermission_Friends_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 谁能加你为好友？ ähnelt.
        /// </summary>
        internal static string Privacy_Chat_AddFriendPermission_Heading {
            get {
                return ResourceManager.GetString("Privacy_Chat_AddFriendPermission_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 只有相互询问 ähnelt.
        /// </summary>
        internal static string Privacy_Chat_AddFriendPermission_Request_Label {
            get {
                return ResourceManager.GetString("Privacy_Chat_AddFriendPermission_Request_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 其他人可以看到你正在运行的应用程序。无论你是在打游戏，听音乐，还是做其他事情。这些设置并不影响你是否显示你在一个频道中。在 &quot;我的频道 &quot;下设置这些设置。 ähnelt.
        /// </summary>
        internal static string Privacy_Chat_Content {
            get {
                return ResourceManager.GetString("Privacy_Chat_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 一般隐私 ähnelt.
        /// </summary>
        internal static string Privacy_Chat_Heading {
            get {
                return ResourceManager.GetString("Privacy_Chat_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 大家好 ähnelt.
        /// </summary>
        internal static string Privacy_Chat_LastOnline_Everybody_Label {
            get {
                return ResourceManager.GetString("Privacy_Chat_LastOnline_Everybody_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 只有朋友 ähnelt.
        /// </summary>
        internal static string Privacy_Chat_LastOnline_Friends_Label {
            get {
                return ResourceManager.GetString("Privacy_Chat_LastOnline_Friends_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 最后一次在线 ähnelt.
        /// </summary>
        internal static string Privacy_Chat_LastOnline_Heading {
            get {
                return ResourceManager.GetString("Privacy_Chat_LastOnline_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 没有人 ähnelt.
        /// </summary>
        internal static string Privacy_Chat_LastOnline_Nobody_Label {
            get {
                return ResourceManager.GetString("Privacy_Chat_LastOnline_Nobody_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 不允许直接联系你的人，会在第一条信息中给你发送请求，你必须同意。没有人可以看到你设置了什么设置。 ähnelt.
        /// </summary>
        internal static string Privacy_Chat_Privacy_Content {
            get {
                return ResourceManager.GetString("Privacy_Chat_Privacy_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 聊天中的隐私 ähnelt.
        /// </summary>
        internal static string Privacy_Chat_Privacy_Heading {
            get {
                return ResourceManager.GetString("Privacy_Chat_Privacy_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 显示在状态中的应用程序 ähnelt.
        /// </summary>
        internal static string Privacy_Chat_ShowStatus_Heading {
            get {
                return ResourceManager.GetString("Privacy_Chat_ShowStatus_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 大家好 ähnelt.
        /// </summary>
        internal static string Privacy_Chat_Status_Everybody_Label {
            get {
                return ResourceManager.GetString("Privacy_Chat_Status_Everybody_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 只有朋友 ähnelt.
        /// </summary>
        internal static string Privacy_Chat_Status_Friends_Label {
            get {
                return ResourceManager.GetString("Privacy_Chat_Status_Friends_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 没有人 ähnelt.
        /// </summary>
        internal static string Privacy_Chat_Status_Label_Label {
            get {
                return ResourceManager.GetString("Privacy_Chat_Status_Label_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 谁能看到你的状态 ähnelt.
        /// </summary>
        internal static string Privacy_Chat_WritingPermission_Heading {
            get {
                return ResourceManager.GetString("Privacy_Chat_WritingPermission_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 如果你将状态设置为隐身，没有人会看到你的活动和是否在线。你的渠道也会被大家所忽视。 ähnelt.
        /// </summary>
        internal static string Privacy_Infotext1 {
            get {
                return ResourceManager.GetString("Privacy_Infotext1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 如果是相互请求，两个人都必须发送好友请求。如果是这种情况，就会自动成为好友。 ähnelt.
        /// </summary>
        internal static string Privacy_Infotext2 {
            get {
                return ResourceManager.GetString("Privacy_Infotext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 点击这里添加节目 ähnelt.
        /// </summary>
        internal static string Privacy_Status_addApp {
            get {
                return ResourceManager.GetString("Privacy_Status_addApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 在这里，您可以更改单个区域或整个设置，以达到以下目的 
        ///重置出厂设置 ähnelt.
        /// </summary>
        internal static string ResetSettings_Description {
            get {
                return ResourceManager.GetString("ResetSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 重置设置 ähnelt.
        /// </summary>
        internal static string ResetSettings_Heading {
            get {
                return ResourceManager.GetString("ResetSettings_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 所有设置 ähnelt.
        /// </summary>
        internal static string ResetSettings_Options_AllSettings {
            get {
                return ResourceManager.GetString("ResetSettings_Options_AllSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 关闭(ESC) ähnelt.
        /// </summary>
        internal static string SaveText {
            get {
                return ResourceManager.GetString("SaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 帐户恢复电子邮件 ähnelt.
        /// </summary>
        internal static string Security_AccountRecoveryHeading {
            get {
                return ResourceManager.GetString("Security_AccountRecoveryHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 查看所有活动 ähnelt.
        /// </summary>
        internal static string Security_AllAktivities {
            get {
                return ResourceManager.GetString("Security_AllAktivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 每一个备份代码，您就可以登录一次您的账户! ähnelt.
        /// </summary>
        internal static string Security_BackupCode_Description {
            get {
                return ResourceManager.GetString("Security_BackupCode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 残障人士 ähnelt.
        /// </summary>
        internal static string Security_BackupCode_Disable {
            get {
                return ResourceManager.GetString("Security_BackupCode_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 下载 ähnelt.
        /// </summary>
        internal static string Security_BackupCode_Download {
            get {
                return ResourceManager.GetString("Security_BackupCode_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 激活 ähnelt.
        /// </summary>
        internal static string Security_BackupCode_Enable {
            get {
                return ResourceManager.GetString("Security_BackupCode_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 备份码 ähnelt.
        /// </summary>
        internal static string Security_BackupCode_Heading {
            get {
                return ResourceManager.GetString("Security_BackupCode_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 显示 ähnelt.
        /// </summary>
        internal static string Security_BackupCode_View {
            get {
                return ResourceManager.GetString("Security_BackupCode_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 更改账户 ähnelt.
        /// </summary>
        internal static string Security_ConnectedEmail_ChangeAccount {
            get {
                return ResourceManager.GetString("Security_ConnectedEmail_ChangeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 最后一次检查日期% ähnelt.
        /// </summary>
        internal static string Security_ConnectedEmail_Check {
            get {
                return ResourceManager.GetString("Security_ConnectedEmail_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 您的链接电子邮件账户 ähnelt.
        /// </summary>
        internal static string Security_ConnectedEmail_Heading {
            get {
                return ResourceManager.GetString("Security_ConnectedEmail_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 查看账户 ähnelt.
        /// </summary>
        internal static string Security_ConnectedEmail_ViewAccount {
            get {
                return ResourceManager.GetString("Security_ConnectedEmail_ViewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 已连接的电子邮件账户 ähnelt.
        /// </summary>
        internal static string Security_ConnectedEmailHeading {
            get {
                return ResourceManager.GetString("Security_ConnectedEmailHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 通过电子邮件、电话号码或用户ID进行注册。 ähnelt.
        /// </summary>
        internal static string Security_ConnectedEmailInfo {
            get {
                return ResourceManager.GetString("Security_ConnectedEmailInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 最后的账户活动 ähnelt.
        /// </summary>
        internal static string Security_LastActivity {
            get {
                return ResourceManager.GetString("Security_LastActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 受到严重保护 ähnelt.
        /// </summary>
        internal static string Security_NotSecure {
            get {
                return ResourceManager.GetString("Security_NotSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 更改账户 ähnelt.
        /// </summary>
        internal static string Security_RecoveryEmail_ChangeAccount {
            get {
                return ResourceManager.GetString("Security_RecoveryEmail_ChangeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 最后一次检查日期% ähnelt.
        /// </summary>
        internal static string Security_RecoveryEmail_Check {
            get {
                return ResourceManager.GetString("Security_RecoveryEmail_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 帐户恢复的电子邮件帐户 ähnelt.
        /// </summary>
        internal static string Security_RecoveryEmail_Heading {
            get {
                return ResourceManager.GetString("Security_RecoveryEmail_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 查看账户 ähnelt.
        /// </summary>
        internal static string Security_RecoveryEmail_ViewAccount {
            get {
                return ResourceManager.GetString("Security_RecoveryEmail_ViewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 保护得好 ähnelt.
        /// </summary>
        internal static string Security_Secure {
            get {
                return ResourceManager.GetString("Security_Secure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 看看你的安全指数。如果我们确定您的账户没有得到足够的保护，我们将立即通知您。 ähnelt.
        /// </summary>
        internal static string Security_SecureBoxInfo_1 {
            get {
                return ResourceManager.GetString("Security_SecureBoxInfo_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 你的连接电子邮件账户具有最高优先级。无论谁能访问这个账户，也可以访问你的其他账户。 ähnelt.
        /// </summary>
        internal static string Security_SecureBoxInfo_2 {
            get {
                return ResourceManager.GetString("Security_SecureBoxInfo_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2 认证系数 ähnelt.
        /// </summary>
        internal static string Security_TwoFactorHeading {
            get {
                return ResourceManager.GetString("Security_TwoFactorHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 更改电话号码 ähnelt.
        /// </summary>
        internal static string Security_TwoFaktor_ChangeNumber {
            get {
                return ResourceManager.GetString("Security_TwoFaktor_ChangeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 最后一次检查日期% ähnelt.
        /// </summary>
        internal static string Security_TwoFaktor_Check {
            get {
                return ResourceManager.GetString("Security_TwoFaktor_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2FA停用 ähnelt.
        /// </summary>
        internal static string Security_TwoFaktor_DisableTwoFaktor {
            get {
                return ResourceManager.GetString("Security_TwoFaktor_DisableTwoFaktor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 激活2FA ähnelt.
        /// </summary>
        internal static string Security_TwoFaktor_EnambleTwoFaktor {
            get {
                return ResourceManager.GetString("Security_TwoFaktor_EnambleTwoFaktor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 通过短信进行双因素认证 ähnelt.
        /// </summary>
        internal static string Security_TwoFaktor_Heading {
            get {
                return ResourceManager.GetString("Security_TwoFaktor_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 您的账户活动 ähnelt.
        /// </summary>
        internal static string Security_YourAccountActivity {
            get {
                return ResourceManager.GetString("Security_YourAccountActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 您的安全指数 ähnelt.
        /// </summary>
        internal static string Security_YourSecurityStatusHeading {
            get {
                return ResourceManager.GetString("Security_YourSecurityStatusHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 为设备设置优先级! 激活新设备的限制! ähnelt.
        /// </summary>
        internal static string Security_YourSecurityStatusInfo {
            get {
                return ResourceManager.GetString("Security_YourSecurityStatusInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 设置 ähnelt.
        /// </summary>
        internal static string SettingsHeading {
            get {
                return ResourceManager.GetString("SettingsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 当程序打开时，更新会自动启动。 ähnelt.
        /// </summary>
        internal static string Updates_AutoUpdate_Description {
            get {
                return ResourceManager.GetString("Updates_AutoUpdate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 当程序打开时，更新会自动启动。 ähnelt.
        /// </summary>
        internal static string Updates_AutoUpdate_Description1 {
            get {
                return ResourceManager.GetString("Updates_AutoUpdate_Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 自动更新 ähnelt.
        /// </summary>
        internal static string Updates_AutoUpdate_Heading {
            get {
                return ResourceManager.GetString("Updates_AutoUpdate_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 自动更新 ähnelt.
        /// </summary>
        internal static string Updates_AutoUpdate_Heading1 {
            get {
                return ResourceManager.GetString("Updates_AutoUpdate_Heading1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 您将收到通知，并可以决定是否立即或稍后安装更新。 ähnelt.
        /// </summary>
        internal static string Updates_AutoUpdateBlock_Description {
            get {
                return ResourceManager.GetString("Updates_AutoUpdateBlock_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 您将收到通知，并可以决定是否立即或稍后安装更新。 ähnelt.
        /// </summary>
        internal static string Updates_AutoUpdateBlock_Description1 {
            get {
                return ResourceManager.GetString("Updates_AutoUpdateBlock_Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 当我很忙时，防止自动更新 ähnelt.
        /// </summary>
        internal static string Updates_AutoUpdateBlock_Heading {
            get {
                return ResourceManager.GetString("Updates_AutoUpdateBlock_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 当我很忙时，防止自动更新 ähnelt.
        /// </summary>
        internal static string Updates_AutoUpdateBlock_Heading1 {
            get {
                return ResourceManager.GetString("Updates_AutoUpdateBlock_Heading1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 当您重新启动应用程序时，更新总是自动下载。 ähnelt.
        /// </summary>
        internal static string Updates_Description_1 {
            get {
                return ResourceManager.GetString("Updates_Description_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 当您重新启动应用程序时，更新总是自动下载。 ähnelt.
        /// </summary>
        internal static string Updates_Description_11 {
            get {
                return ResourceManager.GetString("Updates_Description_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 根据更新的重要程度，我们会在以后给您安装的机会。比如说，如果我们急需用更新来关闭一个安全漏洞，出于安全考虑，即使是中断了你的活动，也会立即安装更新。 ähnelt.
        /// </summary>
        internal static string Updates_Description_2 {
            get {
                return ResourceManager.GetString("Updates_Description_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 根据更新的重要程度，我们会在以后给您安装的机会。比如说，如果我们急需用更新来关闭一个安全漏洞，出于安全考虑，即使是中断了你的活动，也会立即安装更新。 ähnelt.
        /// </summary>
        internal static string Updates_Description_21 {
            get {
                return ResourceManager.GetString("Updates_Description_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 更新 ähnelt.
        /// </summary>
        internal static string Updates_Heading {
            get {
                return ResourceManager.GetString("Updates_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 更新 ähnelt.
        /// </summary>
        internal static string Updates_Heading1 {
            get {
                return ResourceManager.GetString("Updates_Heading1", resourceCulture);
            }
        }
    }
}
