//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWC_VoiceAssistent.db {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class French {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal French() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DWC_VoiceAssistent.db.French", typeof(French).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ajouter une application ähnelt.
        /// </summary>
        internal static string AddFavoritApp1 {
            get {
                return ResourceManager.GetString("AddFavoritApp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Oups, désolé, une erreur s&apos;est produite ! ähnelt.
        /// </summary>
        internal static string DWC_ExeptionMessage1 {
            get {
                return ResourceManager.GetString("DWC_ExeptionMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Assistant linguistique ähnelt.
        /// </summary>
        internal static string DWC_MainMenu_Navigator_Assistent1 {
            get {
                return ResourceManager.GetString("DWC_MainMenu_Navigator_Assistent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jeux ähnelt.
        /// </summary>
        internal static string DWC_MainMenu_Navigator_Games1 {
            get {
                return ResourceManager.GetString("DWC_MainMenu_Navigator_Games1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Accueil ähnelt.
        /// </summary>
        internal static string DWC_MainMenu_Navigator_Home1 {
            get {
                return ResourceManager.GetString("DWC_MainMenu_Navigator_Home1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        internal static string DWC_MainMenu_Navigator_Infos1 {
            get {
                return ResourceManager.GetString("DWC_MainMenu_Navigator_Infos1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Votre profil ähnelt.
        /// </summary>
        internal static string DWC_MainMenu_Navigator_Profile1 {
            get {
                return ResourceManager.GetString("DWC_MainMenu_Navigator_Profile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Commandes ähnelt.
        /// </summary>
        internal static string DWC_MainMenu_Topbar_Commands1 {
            get {
                return ResourceManager.GetString("DWC_MainMenu_Topbar_Commands1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extras ähnelt.
        /// </summary>
        internal static string DWC_MainMenu_Topbar_Extras1 {
            get {
                return ResourceManager.GetString("DWC_MainMenu_Topbar_Extras1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hilfe ähnelt.
        /// </summary>
        internal static string DWC_MainMenu_Topbar_Help1 {
            get {
                return ResourceManager.GetString("DWC_MainMenu_Topbar_Help1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aide ähnelt.
        /// </summary>
        internal static string DWC_MainMenu_Topbar_Info1 {
            get {
                return ResourceManager.GetString("DWC_MainMenu_Topbar_Info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugins ähnelt.
        /// </summary>
        internal static string DWC_MainMenu_Topbar_Plugins1 {
            get {
                return ResourceManager.GetString("DWC_MainMenu_Topbar_Plugins1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paramètres ähnelt.
        /// </summary>
        internal static string DWC_MainMenu_Topbar_Settings1 {
            get {
                return ResourceManager.GetString("DWC_MainMenu_Topbar_Settings1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Site web ähnelt.
        /// </summary>
        internal static string DWC_MainMenu_Topbar_Webside1 {
            get {
                return ResourceManager.GetString("DWC_MainMenu_Topbar_Webside1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vos applications préférées ähnelt.
        /// </summary>
        internal static string FavoritApps1 {
            get {
                return ResourceManager.GetString("FavoritApps1", resourceCulture);
            }
        }
    }
}
