//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWC_VoiceAssistent.db {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Spanish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Spanish() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DWC_VoiceAssistent.db.Spanish", typeof(Spanish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Agregar aplicación ähnelt.
        /// </summary>
        internal static string AddFavoritApp {
            get {
                return ResourceManager.GetString("AddFavoritApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ¡Uy, lo siento, ha habido un error! ähnelt.
        /// </summary>
        internal static string DWC_ExeptionMessage {
            get {
                return ResourceManager.GetString("DWC_ExeptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Asistente de idiomas ähnelt.
        /// </summary>
        internal static string DWC_MainMenu_Navigator_Assistent {
            get {
                return ResourceManager.GetString("DWC_MainMenu_Navigator_Assistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Juegos ähnelt.
        /// </summary>
        internal static string DWC_MainMenu_Navigator_Games {
            get {
                return ResourceManager.GetString("DWC_MainMenu_Navigator_Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inicio ähnelt.
        /// </summary>
        internal static string DWC_MainMenu_Navigator_Home {
            get {
                return ResourceManager.GetString("DWC_MainMenu_Navigator_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Información ähnelt.
        /// </summary>
        internal static string DWC_MainMenu_Navigator_Infos {
            get {
                return ResourceManager.GetString("DWC_MainMenu_Navigator_Infos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Su perfil ähnelt.
        /// </summary>
        internal static string DWC_MainMenu_Navigator_Profile {
            get {
                return ResourceManager.GetString("DWC_MainMenu_Navigator_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comandos ähnelt.
        /// </summary>
        internal static string DWC_MainMenu_Topbar_Commands {
            get {
                return ResourceManager.GetString("DWC_MainMenu_Topbar_Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extras ähnelt.
        /// </summary>
        internal static string DWC_MainMenu_Topbar_Extras {
            get {
                return ResourceManager.GetString("DWC_MainMenu_Topbar_Extras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ayuda ähnelt.
        /// </summary>
        internal static string DWC_MainMenu_Topbar_Help {
            get {
                return ResourceManager.GetString("DWC_MainMenu_Topbar_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Información ähnelt.
        /// </summary>
        internal static string DWC_MainMenu_Topbar_Info {
            get {
                return ResourceManager.GetString("DWC_MainMenu_Topbar_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plugins ähnelt.
        /// </summary>
        internal static string DWC_MainMenu_Topbar_Plugins {
            get {
                return ResourceManager.GetString("DWC_MainMenu_Topbar_Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ajustes ähnelt.
        /// </summary>
        internal static string DWC_MainMenu_Topbar_Settings {
            get {
                return ResourceManager.GetString("DWC_MainMenu_Topbar_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die sitio web ähnelt.
        /// </summary>
        internal static string DWC_MainMenu_Topbar_Webside {
            get {
                return ResourceManager.GetString("DWC_MainMenu_Topbar_Webside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tus aplicaciones favoritas ähnelt.
        /// </summary>
        internal static string FavoritApps {
            get {
                return ResourceManager.GetString("FavoritApps", resourceCulture);
            }
        }
    }
}
